#!/bin/sh
# PekWM start file
# This file is a simple shell script; It gets run on pekwm startup, after 
# the theme and all config has loaded if it is set executable
# (chmod +x start).
#
# This is different from ~/.xinitrc because a normal configuration of 
# .xinitrc you'll run all commands, then launch the window manager last.
#
# It also gets re-run every time pekwm is restarted.
# 
# As for it's usefulness, well, it's up to you. I actually set my background
# from my start file; since it runs after the theme gets loaded, this 
# effectively overrides whatever's in the theme.
# 
# There's probably a few other good uses for it, too. I mainly pushed for it
# because when I was doing fluxbox's docs, people used to complain that there
# wasn't one, and I wanted to avoid that for pekwm. ;) --eyez


nitrogen --restore #wallpaper
tint2 &  #panel
conky -d -c ~/.conky/conkyrc &
conky -d -c ~/.conky/accuw-conkyrc &
/usr/libexec/polkit-gnome-authentication-agent-1 &
#kdeinit4 &
/usr/lib/notify-osd/notify-osd &
gpomme &

sleep 1
# the original
#compton  -t-5 -l-5 -r5 -o1 -m.8 -e.7 -cCz -b
#this one casts white shadow
#compton  -t-3 -l-3 --shadow-radius 3 --shadow-opacity 1 --menu-opacity .8 --frame-opacity .7 --shadow-red .9 --shadow-green .9 --shadow-blue .9 -cCz -b 
#white shadow all around :o
compton  -t-5 -l-5 --shadow-radius 4 --shadow-opacity .85 --menu-opacity .85 --frame-opacity .7 --shadow-red .9 --shadow-green .9 --shadow-blue .9 -Ccz -b

wicd-client -t &

dolphin &

xbindkeys &
#bluedevil-monolithic &
#irexec --daemon &

#qdbus org.kde.kded /kded loadModule keyboard &
qdbus org.kde.kded5 /kded loadModule keyboard

#konsole --name dterm --hide-tabbar --hide-menubar --profile DesktopShell --geometry 640x280+30+480 --nofork -e ncmpcpp &

/home/marietta/scripts/wacom.sh

easystroke &
